/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "@supabase/supabase-js";

const client = () =>
  createClient(
    Deno.env.get("SUPABASE_URL"),
    Deno.env.get("SUPABASE_KEY"),
  );

// Set stores a key-value pair in the database.
export const set = async (key, value) => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_65f4d79e").upsert({
    key,
    value,
  });

  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key) => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_65f4d79e")
    .select("value")
    .eq("key", key)
    .maybeSingle();

  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key) => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_65f4d79e").delete().eq("key", key);

  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (pairs) => {
  const supabase = client();
  const { error } = await supabase
    .from("kv_store_65f4d79e")
    .upsert(pairs.map(({ key, value }) => ({ key, value })));

  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys) => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_65f4d79e")
    .select("value")
    .in("key", keys);

  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys) => {
  const supabase = client();
  const { error } = await supabase
    .from("kv_store_65f4d79e")
    .delete()
    .in("key", keys);

  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix) => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_65f4d79e")
    .select("key, value")
    .like("key", prefix + "%");

  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};